steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west9-docker.pkg.dev/high-science-312722/website-tools/website-image', '.']
  

images:
- 'europe-west9-docker.pkg.dev/high-science-312722/website-tools/website-image'

